#! /bin/bash

source ./opts2map.sh
source ./api.sh
declare -A map
declare -a args=("${@}")
opts2map args map
keyword="${map[0]}"

SUGGESTIONS_DEFAULT_API="$(cat ./api | grep SUGGESTIONS_DEFAULT_API | cut -d ":" -f2,3)"
SUGGESTIONS_HOTSPOT_API="$(cat ./api | grep SUGGESTIONS_HOTSPOT_API | cut -d ":" -f2,3)"
SUGGESTIONS_KEYWORD_API="$(cat ./api | grep SUGGESTIONS_KEYWORD_API | cut -d ":" -f2,3)"

[ ! -z "${map["hotspot"]}" ] && {
    # hotspot suggestions.
    HOTSPOT_NUMS=10
    [[ "${map["hotspot"]}" != "true" ]] && {
        HOTSPOT_NUMS="${map["hotspot"]}"
    }
    __hotspot="$( \
        FETCH_FROM_API \
        "$SUGGESTIONS_HOTSPOT_API" \
        ".data.trending.list[].show_name" \
        "NULL" \
        "limit=$HOTSPOT_NUMS"
    )"
    echo -e "$__hotspot"
} || {
    # default suggestions.
    [ -z "$keyword" ] && {
        __default="$( \
            FETCH_FROM_API \
            "$SUGGESTIONS_DEFAULT_API" \
            ".data.show_name" \
            "NULL"
        )"
        echo -e "$__default"
    } || {
    # keyword suggestions.
        __search="$( \
            FETCH_FROM_API \
            "$SUGGESTIONS_KEYWORD_API" \
            ".result.tag[].value" \
            "NULL" \
            "term=$keyword" \
            "main_ver=v1"
        )"
        echo -e "$__search"
    }
}
