#! /bin/sh

source ./opts2map.sh
declare -A map
declare -a args=("${@}")
opts2map args map
subcmd=${map[0]}

case $subcmd in
    search)
        ;;
    watch)
        ;;
    download)
        ;;
    *)
        # interactive mode using fzf.
        INITIAL_QUERY=""
        SUGGESTIONS_COMMAND="./bili-suggestions $args"
        SEARCH_COMMAND="./bili-search $args"
        FZF_DEFAULT_COMMAND="$SUGGESTIONS_COMMAND '$INITIAL_QUERY' | cat -n"\
            fzf --ansi \
                --with-nth 2..\
                --bind "change:reload:$SUGGESTIONS_COMMAND {q} | cat -n || true" \
                --bind "ctrl-s:reload:$SEARCH_COMMAND \"{}\" | cat -n" \
                --bind "enter:execute(mpv ~/Music/123木头人.flac)" \
                --disabled --query "$INITIAL_QUERY" | awk '{print $1}'
        #\
        #            | awk '{print $1}')
esac
